version: '3.8'

services:
  scraper-jugadores:
    build: .
    container_name: scraper-jugadores
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - SCRAPER_WORKERS=1
    restart: unless-stopped
    
  # Para ejecutar múltiples contenedores en paralelo
  scraper-jugadores-1:
    build: .
    container_name: scraper-jugadores-1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1
      - SCRAPER_WORKERS=3
    restart: unless-stopped
    
  scraper-jugadores-2:
    build: .
    container_name: scraper-jugadores-2
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2
      - SCRAPER_WORKERS=3
    restart: unless-stopped
    
  scraper-jugadores-3:
    build: .
    container_name: scraper-jugadores-3
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3
      - SCRAPER_WORKERS=3
    restart: unless-stopped